修复fbo  viewport设置错误
ChillingVan/android-openGL-canvas pull request #98
Opened 2021-06-03 12:29 UTC by feiyin0719

viewport应该设置为fbo的宽高

2021-06-05 03:09 UTC, ChillingVan commented on canvasgl/src/main/java/com/chillingvan/canvasgl/glcanvas/GLES20Canvas.java
> +        GLES20.glViewport(0, 0, (int)width, (int)height);
请问是如何发现这里有问题的？

2021-06-05 04:05 UTC, ChillingVan commented on canvasgl/src/main/java/com/chillingvan/canvasgl/glcanvas/GLES20Canvas.java
> +        GLES20.glViewport(0, 0, (int)width, (int)height);
这个改法应该不对，这个会限制了绘制的可视区域的

2021-06-05 04:16 UTC, feiyin0719 commented on canvasgl/src/main/java/com/chillingvan/canvasgl/glcanvas/GLES20Canvas.java
> +        GLES20.glViewport(0, 0, (int)width, (int)height);
当需要离屏渲染的纹理图大于屏幕大小的时候，就会导致绘制错误，我在使用filter group渲染一个大于屏幕大小的纹理图时候发现的

2021-06-05 05:16 UTC, ChillingVan commented on canvasgl/src/main/java/com/chillingvan/canvasgl/glcanvas/GLES20Canvas.java
> +        GLES20.glViewport(0, 0, (int)width, (int)height);
> 
> 
> 当需要离屏渲染的纹理图大于屏幕大小的时候，就会导致绘制错误，我在使用filter group渲染一个大于屏幕大小的纹理图时候发现的

那可能最好先考虑把ViewPort大小设大，离屏渲染的话用OffScreenCanvas是可以传宽高的，宽高设大一些。
然后这里可能考虑一下判断width, height大于ScreenWidth ScreenHeight才能设进去ViewPort，这个方案还要再评估一下。
现在直接用width, height，用draw(bitmap, x, y, w, h)这个方法会导致位置和大小都不对的。

2021-06-05 05:18 UTC, ChillingVan requested changes
Cannot use glViewport(w, h) to replace glViewPort(screenW, screenH). This will cause draw(bitmap, x, y, w, h) error.

2021-06-05 05:18 UTC, ChillingVan commented on canvasgl/src/main/java/com/chillingvan/canvasgl/glcanvas/GLES20Canvas.java
> +        GLES20.glViewport(0, 0, (int)width, (int)height);
高斯模糊那个我测了下没问题，可以单独提。这个我先reject了。

2021-06-06 06:52 UTC, feiyin0719 commented on canvasgl/src/main/java/com/chillingvan/canvasgl/glcanvas/GLES20Canvas.java
> +        GLES20.glViewport(0, 0, (int)width, (int)height);
这里我一开始没看清楚。 我以为是开fbo的时候才做viewport设置的。 请教一下为什么每次绘制都做viewport设置，我理解只有屏幕宽高发生变化的时候才需要做设置

2021-06-06 07:12 UTC, feiyin0719 commented on canvasgl/src/main/java/com/chillingvan/canvasgl/glcanvas/GLES20Canvas.java
> +        GLES20.glViewport(0, 0, (int)width, (int)height);
重新修改了下。你再看下。这里应该用的是mWidth。这样如果开启了fbo的话就用的fbo里面纹理的宽高，如果没有开启的话也是screen的宽高

2021-06-07 01:52 UTC, feiyin0719 commented on canvasgl/src/main/java/com/chillingvan/canvasgl/glcanvas/GLES20Canvas.java
> +        GLES20.glViewport(0, 0, (int)width, (int)height);
这里我看了下gallery源码好像是在开启新的fbo的时候才会去设置viewport

2021-06-12 11:59 UTC, ChillingVan commented on canvasgl/src/main/java/com/chillingvan/canvasgl/glcanvas/GLES20Canvas.java
> +        GLES20.glViewport(0, 0, (int)width, (int)height);
> 
> 
> 这里我一开始没看清楚。 我以为是开fbo的时候才做viewport设置的。 请教一下为什么每次绘制都做viewport设置，我理解只有屏幕宽高发生变化的时候才需要做设置

这个是因为要把物体放置在ViewPort中心才能比较好地计算位置变换所需要的矩阵

2022-12-23 09:16 UTC, merged